/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardTournamentsIndexRouteImport } from './routes/dashboard/tournaments/index'
import { Route as DashboardAthletesIndexRouteImport } from './routes/dashboard/athletes/index'
import { Route as DashboardTournamentsIdRouteImport } from './routes/dashboard/tournaments/$id'
import { Route as ApiTournamentSocketTokenRouteImport } from './routes/api/tournament/socket-token'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardTournamentsIdBuilderRouteImport } from './routes/dashboard_.tournaments.$id.builder'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardTournamentsIndexRoute =
  DashboardTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAthletesIndexRoute = DashboardAthletesIndexRouteImport.update({
  id: '/athletes/',
  path: '/athletes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentsIdRoute = DashboardTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiTournamentSocketTokenRoute =
  ApiTournamentSocketTokenRouteImport.update({
    id: '/api/tournament/socket-token',
    path: '/api/tournament/socket-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTournamentsIdBuilderRoute =
  DashboardTournamentsIdBuilderRouteImport.update({
    id: '/dashboard_/tournaments/$id/builder',
    path: '/dashboard/tournaments/$id/builder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/tournament/socket-token': typeof ApiTournamentSocketTokenRoute
  '/dashboard/tournaments/$id': typeof DashboardTournamentsIdRoute
  '/dashboard/athletes/': typeof DashboardAthletesIndexRoute
  '/dashboard/tournaments/': typeof DashboardTournamentsIndexRoute
  '/dashboard/tournaments/$id/builder': typeof DashboardTournamentsIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/tournament/socket-token': typeof ApiTournamentSocketTokenRoute
  '/dashboard/tournaments/$id': typeof DashboardTournamentsIdRoute
  '/dashboard/athletes': typeof DashboardAthletesIndexRoute
  '/dashboard/tournaments': typeof DashboardTournamentsIndexRoute
  '/dashboard/tournaments/$id/builder': typeof DashboardTournamentsIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/tournament/socket-token': typeof ApiTournamentSocketTokenRoute
  '/dashboard/tournaments/$id': typeof DashboardTournamentsIdRoute
  '/dashboard/athletes/': typeof DashboardAthletesIndexRoute
  '/dashboard/tournaments/': typeof DashboardTournamentsIndexRoute
  '/dashboard_/tournaments/$id/builder': typeof DashboardTournamentsIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/$'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/tournament/socket-token'
    | '/dashboard/tournaments/$id'
    | '/dashboard/athletes/'
    | '/dashboard/tournaments/'
    | '/dashboard/tournaments/$id/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/tournament/socket-token'
    | '/dashboard/tournaments/$id'
    | '/dashboard/athletes'
    | '/dashboard/tournaments'
    | '/dashboard/tournaments/$id/builder'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/_auth/login'
    | '/api/$'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/tournament/socket-token'
    | '/dashboard/tournaments/$id'
    | '/dashboard/athletes/'
    | '/dashboard/tournaments/'
    | '/dashboard_/tournaments/$id/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiTournamentSocketTokenRoute: typeof ApiTournamentSocketTokenRoute
  DashboardTournamentsIdBuilderRoute: typeof DashboardTournamentsIdBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/tournaments/': {
      id: '/dashboard/tournaments/'
      path: '/tournaments'
      fullPath: '/dashboard/tournaments/'
      preLoaderRoute: typeof DashboardTournamentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/athletes/': {
      id: '/dashboard/athletes/'
      path: '/athletes'
      fullPath: '/dashboard/athletes/'
      preLoaderRoute: typeof DashboardAthletesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tournaments/$id': {
      id: '/dashboard/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/dashboard/tournaments/$id'
      preLoaderRoute: typeof DashboardTournamentsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/tournament/socket-token': {
      id: '/api/tournament/socket-token'
      path: '/api/tournament/socket-token'
      fullPath: '/api/tournament/socket-token'
      preLoaderRoute: typeof ApiTournamentSocketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/tournaments/$id/builder': {
      id: '/dashboard_/tournaments/$id/builder'
      path: '/dashboard/tournaments/$id/builder'
      fullPath: '/dashboard/tournaments/$id/builder'
      preLoaderRoute: typeof DashboardTournamentsIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTournamentsIdRoute: typeof DashboardTournamentsIdRoute
  DashboardAthletesIndexRoute: typeof DashboardAthletesIndexRoute
  DashboardTournamentsIndexRoute: typeof DashboardTournamentsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTournamentsIdRoute: DashboardTournamentsIdRoute,
  DashboardAthletesIndexRoute: DashboardAthletesIndexRoute,
  DashboardTournamentsIndexRoute: DashboardTournamentsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiTournamentSocketTokenRoute: ApiTournamentSocketTokenRoute,
  DashboardTournamentsIdBuilderRoute: DashboardTournamentsIdBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
