/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardTournamentIndexRouteImport } from './routes/dashboard/tournament/index'
import { Route as DashboardAthleteIndexRouteImport } from './routes/dashboard/athlete/index'
import { Route as DashboardTournamentIdRouteImport } from './routes/dashboard/tournament/$id'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardTournamentIdBuilderRouteImport } from './routes/dashboard_.tournament.$id.builder'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardTournamentIndexRoute =
  DashboardTournamentIndexRouteImport.update({
    id: '/tournament/',
    path: '/tournament/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAthleteIndexRoute = DashboardAthleteIndexRouteImport.update({
  id: '/athlete/',
  path: '/athlete/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentIdRoute = DashboardTournamentIdRouteImport.update({
  id: '/tournament/$id',
  path: '/tournament/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTournamentIdBuilderRoute =
  DashboardTournamentIdBuilderRouteImport.update({
    id: '/dashboard_/tournament/$id/builder',
    path: '/dashboard/tournament/$id/builder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/tournament/$id': typeof DashboardTournamentIdRoute
  '/dashboard/athlete': typeof DashboardAthleteIndexRoute
  '/dashboard/tournament': typeof DashboardTournamentIndexRoute
  '/dashboard/tournament/$id/builder': typeof DashboardTournamentIdBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/tournament/$id': typeof DashboardTournamentIdRoute
  '/dashboard/athlete': typeof DashboardAthleteIndexRoute
  '/dashboard/tournament': typeof DashboardTournamentIndexRoute
  '/dashboard/tournament/$id/builder': typeof DashboardTournamentIdBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/tournament/$id': typeof DashboardTournamentIdRoute
  '/dashboard/athlete/': typeof DashboardAthleteIndexRoute
  '/dashboard/tournament/': typeof DashboardTournamentIndexRoute
  '/dashboard_/tournament/$id/builder': typeof DashboardTournamentIdBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/$'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/tournament/$id'
    | '/dashboard/athlete'
    | '/dashboard/tournament'
    | '/dashboard/tournament/$id/builder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/tournament/$id'
    | '/dashboard/athlete'
    | '/dashboard/tournament'
    | '/dashboard/tournament/$id/builder'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/_auth/login'
    | '/api/$'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/tournament/$id'
    | '/dashboard/athlete/'
    | '/dashboard/tournament/'
    | '/dashboard_/tournament/$id/builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  DashboardTournamentIdBuilderRoute: typeof DashboardTournamentIdBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/tournament/': {
      id: '/dashboard/tournament/'
      path: '/tournament'
      fullPath: '/dashboard/tournament'
      preLoaderRoute: typeof DashboardTournamentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/athlete/': {
      id: '/dashboard/athlete/'
      path: '/athlete'
      fullPath: '/dashboard/athlete'
      preLoaderRoute: typeof DashboardAthleteIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tournament/$id': {
      id: '/dashboard/tournament/$id'
      path: '/tournament/$id'
      fullPath: '/dashboard/tournament/$id'
      preLoaderRoute: typeof DashboardTournamentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/tournament/$id/builder': {
      id: '/dashboard_/tournament/$id/builder'
      path: '/dashboard/tournament/$id/builder'
      fullPath: '/dashboard/tournament/$id/builder'
      preLoaderRoute: typeof DashboardTournamentIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTournamentIdRoute: typeof DashboardTournamentIdRoute
  DashboardAthleteIndexRoute: typeof DashboardAthleteIndexRoute
  DashboardTournamentIndexRoute: typeof DashboardTournamentIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTournamentIdRoute: DashboardTournamentIdRoute,
  DashboardAthleteIndexRoute: DashboardAthleteIndexRoute,
  DashboardTournamentIndexRoute: DashboardTournamentIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  DashboardTournamentIdBuilderRoute: DashboardTournamentIdBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
